### ISSUE TITLE
Provision to override `WOOSMAP_PUBLIC_KEY` used for JS samples

### ISSUE THREAD

**Issue by shwetadeshmukh** [Woosmap/js-samples#21]
### What?

Currently all the maps js samples use a common woosmap public key defined in an environment file that cannot be changed.
This key may not necessarily have all the woosmap products enabled restricting some samples to work.

### Why?

Some samples require specific woosmap products enabled e.g. All Indoor API samples need only `INDOOR API` and `MAP API` enabled to work. 
Whereas the samples for displaying just markers or shapes may not require a key that has INDOOR product enabled. Therefore there should be an ability to override the woosmap public key being used.

**Comment by gaelsimon** [comment]
I'm closing this as you can override the key by using:
`"WOOSMAP_API_KEY": "woos-xxxxx-xxxxx-xxxxx-xxxxx",`
in the sample.json file.

**Comment by shwetadeshmukh** [comment]
> WOOSMAP_API_KEY



> I'm closing this as you can override the key by using: `"WOOSMAP_API_KEY": "woos-xxxxx-xxxxx-xxxxx-xxxxx",` in the sample.json file.
It is `WOOSMAP_PUBLIC_API_KEY` right? and not `WOOSMAP_API_KEY`

**Comment by gaelsimon** [comment]
> > WOOSMAP_API_KEY
> 
> > I'm closing this as you can override the key by using: `"WOOSMAP_API_KEY": "woos-xxxxx-xxxxx-xxxxx-xxxxx",` in the sample.json file.
> > It is `WOOSMAP_PUBLIC_API_KEY` right? and not `WOOSMAP_API_KEY`
> > Just wanted to confirm, the existing used in dev docs for all indoor samples `woos-2a4488cc-3e65-3af1-9057-41c4b646ced1` gives me 403 errors. Is it because of the domain restrictions?

Yes, `WOOSMAP_PUBLIC_API_KEY`
